Adds Austin's R2 Mode to Config Branch, Reworked Bootsel and Config bindings
JonnyHaystack/HayBox pull request #87
Opened 2024-12-28 02:37 UTC by GrammyMoney

- Austin added Rivals 2 Mode to config branch
- Austin added hold R on plugin to clear config file (this change in config.cpp is optional, I have personally disabled it in my fork to avoid accidents)
- Reworked Config and Bootsel for more "user-friendly" experience now that bootsel is a much rarer input

1. Bootsel moved to input RT1 (defaults to A in standard OF1 pinout)
2. Config backend moved to input MB1 (defaults to start in standard OF1 pinout)

This will allow for end users to hold start while accessing config mode, which will be a much more common occurance than bootsel now that remapping is possible.

Bootsel is still very accessible with the A button on plugin, and also avoids the pitfall of sharing any buttons with common game mode bindings (I find that many users accidentally hold the game mode combos on plugin, which causes bootsel, which can be very confusing for new users). Now holding A is an intentional decision, while accidental holding of a game mode just boots into config mode, a much less overwhelming issue.

This also allows all currently supported GUI remappers (Remapp.ing & Remap.box) to use "hold start while plugging in controller" for the remapper UI's without maintaining widely varying forks for third-party support.

Thank you for your consideration.

Cheers goats

2025-01-18 12:14 UTC, JonnyHaystack requested changes

2025-01-18 12:14 UTC, JonnyHaystack commented on config/pico/config.cpp
> +    { BTN_RF8, 18 }, // MidShield
I'd like to leave these comments out as it's not related to the change of adding Rivals 2 mode and it could also be confusing as these only make sense to someone who's used to Melee mode.

The plan was to have graphics for each device config showing the physical layout and how the button codes match up to each controller. Maybe your layout editor thing (https://remapp.ing/editor) could be useful for this, but I'm not sure if it has a way to just show the physical button names yet?

2025-01-18 12:14 UTC, JonnyHaystack commented on HAL/pico/include/config_defaults.hpp
> +    },
```suggestion
        },
    },
```

2025-01-18 12:14 UTC, JonnyHaystack commented on HAL/pico/include/config_defaults.hpp
> +            .activation_binding = { BTN_MB1 }, //C-Down
See comment below:
> I'd like to leave these comments out as it's not related to the change of adding Rivals 2 mode and it could also be confusing as these only make sense to someone who's used to Melee mode.

2025-01-18 12:14 UTC, JonnyHaystack commented on HAL/pico/include/config_defaults.hpp
> +    .game_mode_configs = {
```suggestion
    .game_mode_configs = {
```

2025-01-18 12:14 UTC, JonnyHaystack commented on HAL/pico/include/config_defaults.hpp
> +            .mode_id = MODE_ULTIMATE,
```suggestion
            .mode_id = MODE_ULTIMATE,
```

2025-01-18 12:14 UTC, JonnyHaystack commented on HAL/pico/include/config_defaults.hpp
> +        .crouch_walk_os = false,
```suggestion
        .crouch_walk_os = false,
```
Please remove trailing whitespace (ideally you'd run clang-format on everything as well)

2025-01-18 23:26 UTC, GrammyMoney commented on config/pico/config.cpp
> +    { BTN_RF8, 18 }, // MidShield
You can make a layout with no button mappings and it will show just the physical buttons (like attached)
![image](https://github.com/user-attachments/assets/02120c46-51f1-4ed0-97c2-66960f5b0ad8)

2025-01-18 23:26 UTC, GrammyMoney commented on config/pico/config.cpp
> +    { BTN_RF8, 18 }, // MidShield
^this is the OF1 layout with no mappings on the selected layout view (in this case keyboard mode).

2025-01-18 23:32 UTC, GrammyMoney commented on HAL/pico/include/config_defaults.hpp
> +            .mode_id = MODE_ULTIMATE,
ran formatter, fixed whitespace issues

2025-01-18 23:33 UTC, GrammyMoney commented on HAL/pico/include/config_defaults.hpp
> +            .activation_binding = { BTN_MB1 }, //C-Down
Removed Bootsel/Config rework from this PR, will open a seperate one after merge

2025-01-18 23:33 UTC, GrammyMoney commented on config/pico/config.cpp
> +    { BTN_RF8, 18 }, // MidShield
removed layout comments from general config files

2025-01-18 23:34 UTC, GrammyMoney commented on config/pico/config.cpp
> +    if (inputs.rf5 || !persistence.LoadConfig(config)) { //hold R on plugin to overwrite config
removed bootsel rework

2025-01-18 23:35 UTC, GrammyMoney commented
Newest commit removes bootsel rework and formatting issues, as well as comments referring to melee mode in config files.

2025-01-20 12:38 UTC, JonnyHaystack requested changes
Found some stuff I missed the first time round, also some changes added by this latest commit which shouldn't have been, and I've pointed out where a couple of comments were marked as resolved that were not actually resolved - please check those again.

2025-01-20 12:38 UTC, JonnyHaystack commented on HAL/pico/include/config_defaults.hpp
> +    GameModeConfig { //even with all GameModeConfigs commented out besides one, the code works the same and switches modes the same
Sorry I missed this the first time but could you remove these comments as well as they don't really make sense to leave there outside the context of this PR

2025-01-20 12:38 UTC, JonnyHaystack commented on .vscode/extensions.json
> +}
Please remove changes to this file

2025-01-20 12:38 UTC, JonnyHaystack commented on HAL/pico/include/config_defaults.hpp
> +    },
Doesn't seem like this suggestion was applied

2025-01-20 12:38 UTC, JonnyHaystack commented on src/core/mode_selection.cpp
> +#include "modes/Rivals2.hpp"
Has not been addressed

2025-01-20 12:39 UTC, JonnyHaystack commented on config/pico/config.cpp
> +    { BTN_RF8, 18 },
Please also undo the formatting changes here. There shouldn't be any changes to this file for this PR.

2025-01-23 08:20 UTC, GrammyMoney commented on config/pico/config.cpp
> +    { BTN_RF8, 18 },
This was auto-formatted in clang-format, I can add a /* to disable, but either way it will change the file on commit

2025-01-24 13:25 UTC, JonnyHaystack commented on config/pico/config.cpp
> +    { BTN_RF8, 18 },
Looks like it's changed (for the better) in new version of clang-format so marking as resolved

2025-01-24 13:30 UTC, JonnyHaystack requested changes
We're almost there 😅

2025-01-24 13:30 UTC, JonnyHaystack commented on .vscode/extensions.json
> +}
This is still showing as changed because you've removed the newline at the end of the file so please add that back

2025-01-24 13:30 UTC, JonnyHaystack commented on HAL/pico/include/config_defaults.hpp
> +            .activation_binding = { BTN_MB1 },
This will be conflicting with the bootsel binding at the moment so can you revert the change to this line for now and it can be changed in a future PR

2025-01-26 02:19 UTC, GrammyMoney commented
New commit addresses final 2 change requests

2025-01-26 20:22 UTC, JonnyHaystack approved these changes

2025-01-26 20:23 UTC, merged